language: "c++"
install: "echo"

script: "./scripts/linux/ubuntu/install_dependencies.sh"

branches:
   only:
     - master
notifications:
  recipients:
    - gabriel@soixantecircuits.fr
  email:
    on_success: change
    on_failure: always